# Generated by Django 5.2.1 on 2025-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quize_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(choices=[('question1', models.CharField(max_length=100)), ('question2', models.CharField(max_length=100)), ('question3', models.CharField(max_length=100)), ('question4', models.CharField(max_length=100))], default='NULL', max_length=50),
        ),
    ]
